name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # If you have private packages in GitHub Packages, enable the following NuGet feed step
      - name: Configure private NuGet feed
        run: |
          dotnet nuget add source \
            --username ihaszkaroly \
            --password ${{ secrets.WEBSHARPER_FEED }} \
            --store-password-in-clear-text \
            --name github-packages \
            https://nuget.pkg.github.com/ihaszkaroly/index.json

      # Continue with SDK and build steps
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
