name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read    # for actions/checkout
  pages: write      # for deploying to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore .NET global tools
        run: dotnet tool restore

      - name: Compile & bundle (Fable → Webpack)
        run: |
          dotnet fable src/App.fsproj \
            --optimize \
            --outDir docs \
            --run npx webpack --mode production --output-path docs

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
